- .github/pull_request_template.md
- add template pull request
- None
- None
- None
> feat: create template pull request

- src/components/Button.tsx
- src/index.tsx
Update PR to move component to components folder
> chore: move component to components folder

- babel.config.js
- example/babel.config.js
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
> feat: install reanimated

- src/core/BaseProvider.tsx
- src/core/extendTheme.tsx
- src/index.tsx
- src/theme/theme.ts
> chore: export component

- example/.ondevice/storybook.requires.js
- example/src/stories/Card.stories.tsx
- src/__tests__/Card.test.tsx
- src/__tests__/__snapshots__/Card.test.tsx.snap
- src/components/Card/Card.tsx
- src/components/index.ts
- src/helpers/metrics.ts
- src/index.tsx
- src/theme/base/colors.ts
> feat: implement card component

- package.json
> fix: remove reanimated from dependencies

- example/src/stories/Slider.stories.tsx
- jest.config.json
- src/components/Accordion/AccordionItem.tsx
- src/components/Button/Button.tsx
- src/components/Card/Card.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/CodeInput/CodeInput.tsx
- src/components/Icon/Icon.tsx
- src/components/Progress/Progress.tsx
- src/components/RadioButton/Bounceable.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/Slider/Slider.tsx
- src/components/Slider/SliderFixed.tsx
- src/components/Slider/SliderFixedRange.tsx
- src/components/Slider/SliderRange.tsx
- src/components/Slider/components/Thumb.tsx
- src/components/Slider/components/Track.tsx
- src/components/Slider/components/TrackPoint.tsx
- src/components/Text/Text.tsx
- src/components/TextInput/TextInputFlat.tsx
- src/components/TextInput/TextInputOutlined.tsx
- src/theme/base/spacing.ts
> fix: type all components

- package.json
- src/index.tsx
- type.ts
replace "prepack" to "prepare" for support builder-bob when installed by git URL
remove duplicate export
IDE doesn't support suggested property typescripts
> fix: generate lib module

- src/components/Button/Button.tsx
- src/components/Text/Text.tsx
> fix: missing export text and extend button

- src/__tests__/__snapshots__/Card.test.tsx.snap
- src/components/Card/Card.tsx
> fix: fix card test file

- src/components/Button/Button.tsx
> fix: add field custom text of button

- src/components/Checkbox/Checkbox.tsx
- src/theme/components/Checkbox.ts
- src/theme/components/index.ts
- Fixing borderRadius of Checkbox
- Adding theme for Checkbox like Button
> feat: fix borderRadius and adding theme for Checkbox

- src/theme/components/Text.ts
- src/theme/components/index.ts
> feat: implement text theme

- src/components/Button/Button.tsx
> fix: implement field for button

- src/components/Button/Button.tsx
- src/components/Button/ButtonTransparent.tsx
Fix for issue when passing disabledColor to button doesn't working
> fix: disabledColor doesn't work

- .eslintrc.js
- example/src/stories/Button.stories.tsx
- example/src/stories/Text.stories.tsx
- src/components/Button/Button.tsx
- src/components/Text/Text.tsx
- src/components/TextInput/TextInput.tsx
- src/components/TextInput/TextInputFlat.tsx
- src/components/TextInput/TextInputOutlined.tsx
- src/components/TextInput/components/CustomIcon.tsx
- src/components/TextInput/components/ErrorText.tsx
- src/components/index.ts
> fix: wrong Typescript styled component

- example/src/stories/Button.stories.tsx
- src/components/Button/Button.tsx
> fix: button style

- example/src/stories/Button.stories.tsx
- src/__tests__/CodeInput.test.tsx
- src/__tests__/RadioButton.test.tsx
- src/__tests__/TextInput.test.tsx
- src/components/Button/Button.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/CodeInput/CodeInput.tsx
- src/components/Progress/Progress.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/Slider/SliderFixedRange.tsx
- src/components/Slider/SliderRange.tsx
- src/components/Slider/components/Thumb.tsx
- src/components/Slider/components/TrackPoint.tsx
- src/components/Text/Text.tsx
- src/components/TextInput/TextInput.tsx
- src/components/index.ts
* fix: wrong Typescript styled component
* fix: wrong TextInput styled component
* feat: render label button based on typeof children
* fix: wrong styled in component continue
* fix: wrong styled components
---------
OR
Video link
> fix: wrong styled component (#76)

- package.json
- src/components/Button/Button.tsx
- src/components/CodeInput/CodeInput.tsx
- src/components/TextInput/TextInput.tsx
> fix: refactor code input

- src/components/Button/Button.tsx
- src/components/CodeInput/CodeInput.tsx
- src/components/TextInput/TextInput.tsx
* fix: remove borderBottomWidth
* fix: replace to TextInput
* fix: change to repack and remove comment
* fix: replace to forwardRef
* fix: replace to prepack
OR
Video link
> fix: refactor code input (#79)

- src/__tests__/Cursor.test.tsx
- src/__tests__/Slider.test.tsx
- src/components/Slider/Slider.tsx
- src/components/Slider/components/TrackPoint.tsx
- src/components/index.ts
> fix: update unit test for Slider and Cursor components

- src/__tests__/__snapshots__/Card.test.tsx.snap
- src/components/Button/Button.tsx
- src/components/Card/Card.tsx
- src/components/Checkbox/Checkbox.tsx
- src/core/BaseProvider.tsx
- src/hooks/useTheme.tsx
- src/theme/base/borderWidths.ts
- src/theme/base/opacity.ts
- src/theme/base/sizes.ts
- src/theme/base/spacing.ts
- src/theme/base/typography.ts
Test file cannot get theme's properties
> fix: test file cannot get theme's properties

- example/src/stories/CodeInput.stories.tsx
- src/__tests__/CodeInput.test.tsx
- src/components/CodeInput/CodeInput.tsx
> feat: add onClear method for code input component

- package.json
- src/components/Button/Button.tsx
- src/components/RadioButton/RadioButton.tsx
- tsconfig.json
Refactor for Typescript configuration
OR
Video link
> feat: refactor component

- src/components/RadioButton/RadioButton.tsx
> fix: ensure radio button is circular on all devices

- README.md
- package.json
- src/components/Button/Button.tsx
- src/components/CodeInput/CodeInput.tsx
- src/components/CodeInput/README.md
- src/components/RadioButton/RadioButton.tsx
- src/components/Text/Text.tsx
- tsconfig.json
> release 0.5.0
